FitnessTracker/Controllers/IdentityController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using FitnessTracker.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FitnessTracker.Client.ViewModels.Identity;
using FitnessTracker.Client.Services.Identity;
using static FitnessTracker.Infrastructure.InfrastructureConstants;
using FitnessTracker.Controllers;

namespace FitnessTracker.Client.Controllers
{
    public class IdentityController : AdministrationController
    {
        private readonly IIdentityService identityService;
        private readonly IMapper mapper;

        public IdentityController(
            IIdentityService identityService,
            IMapper mapper)
        {
            this.identityService = identityService;
            this.mapper = mapper;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginFormModel model)
            => await this.Handle(
                async () =>
                {
                    var result = await this.identityService
                        .Login(this.mapper.Map<UserInputModel>(model));

                    this.Response.Cookies.Append(
                        AuthenticationCookieName,
                        result.Token,
                        new CookieOptions
                        {
                            HttpOnly = true,
                            Secure = false,
                            MaxAge = TimeSpan.FromDays(1)
                        });
                },
                success: RedirectToAction(nameof(HomeController.Homepage), "Home"),
                failure: View("../Home/Index", model));

        [AuthorizeAdministrator]
        public IActionResult Logout()
        {
            this.Response.Cookies.Delete(AuthenticationCookieName);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

FitnessTracker/Controllers/TrackingController.cs
using System.Threading.Tasks;
using AutoMapper;
using FitnessTracker.Client.Services.Identity;
using FitnessTracker.Client.Services.Meals;
using FitnessTracker.Client.Services.Recipes;
using FitnessTracker.Client.Services.Workouts;
using FitnessTracker.Client.ViewModels.Meals;
using FitnessTracker.Client.ViewModels.Tracking;
using FitnessTracker.Client.ViewModels.Workouts;
using FitnessTracker.Controllers;
using FitnessTracker.Services.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FitnessTracker.Client.Controllers
{
    public class TrackingController : Controller
    {
        private readonly IIdentityService identityService;
        private readonly IRecipesService recipesService;
        private readonly IMapper mapper;
        private readonly IWorkoutsService workoutsService;
        private readonly ICurrentUserService currentUser;
        private readonly IMealsService mealsService;

        public TrackingController(
            IIdentityService identityService,
            IRecipesService recipesService,
            IMapper mapper,
            IWorkoutsService workoutsService,
            ICurrentUserService currentUser,
            IMealsService mealsService)
        {
            this.identityService = identityService;
            this.recipesService = recipesService;
            this.mapper = mapper;
            this.workoutsService = workoutsService;
            this.currentUser = currentUser;
            this.mealsService = mealsService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TrackWorkout()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> TrackMeal(TrackingFormModel model)
        {
            var param = this.mapper.Map<MealInputModel>(model);
            var result = await this.mealsService.TrackMeal(param);
            return RedirectToAction("Index", "Home");
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> TrackWorkout(TrackingWorkoutModel model)
        {
            var param = this.mapper.Map<WorkoutInputModel>(model);
            var result = await this.workoutsService.TrackWorkout(param);
            return RedirectToAction("Index", "Home");
        }

    }
}

FitnessTracker/Views/Shared/_Layout.cshtml
@using FitnessTracker.Infrastructure
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fitness Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (this.User.IsAdministrator())
                {
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fitness Tracker</a>
                            <a class="float-left" style="text-decoration: none">Welcome, @User.Identity.Name</a>
                                            <a class="float-left" asp-area="" asp-controller="Home" asp-action="PostRecipe">Post Recipe</a>
                                                            <a class="float-left" asp-area="" asp-controller="Tracking" asp-action="Index">Track Meal</a>
                                                                            <a class="float-left" asp-area="" asp-controller="Tracking" asp-action="TrackWorkout">Track Workout</a>
                                                                                            <a class="float-right" asp-area="" asp-controller="Identity" asp-action="Logout">Logout</a> }
                                                                                        else
                                                                                        {
                                                                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fitness Tracker</a>}

                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>